In [1]:
import numpy as np

In [4]:
#Q1

sampleArray = np.array([[100 ,200, 300], [400, 500, 600], [700, 800, 900]])

In [6]:
#printing numbers from third column

sampleArray[:,2]

array([300, 600, 900])

In [19]:
#Q2

x1 = np.arange(9).reshape(3,3)
x2 = np.arange(3)
x1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
# Array Multiplication
x1*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [16]:
x2

array([0, 1, 2])

In [31]:
x1*x2

array([[ 0,  1,  4],
       [ 0,  4, 10],
       [ 0,  7, 16]])

In [30]:
#Matrix multiplication multiplies corresponding elements in matrices and returns their sum
X1 = [3,3,3]
X2 = [2,2,2]
X3 = [[4],[4],[4]]


print(np.matmul(X2,X1))
print(np.matmul(X1,X3))

18
[36]


In [64]:
#Q3

b = np.arange(20,40,2)
d = b[b%2==0]



array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [42]:
#Q4
arr1=[1,2,3,4,5]
arr2=[6,7,8,9,10]

arr1+arr2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [43]:
#Q5
arr =[[1,2,3],[4,5,6],[7,8,9]]

print("Mean is ", np.mean(arr))
print("Standard deviation is ", np.std(arr))
print("Variance deviation is ", np.var(arr))



Mean is  5.0
Standard deviation is  2.581988897471611
Variance deviation is  6.666666666666667


In [47]:
#Q6

a = np.arange(16)
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
#Q7

a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])

print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))


[-2. -2. -1.  0.  1.  1.  2.]
[-1. -1. -0.  1.  2.  2.  2.]
[-2. -2. -0.  0.  2.  2.  2.]


In [49]:
#Q8

a = np.array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

b = np.sum(a,axis=0)
b


array([12, 15, 18])

In [51]:
#Q9

a= np.array([[6,1,1], [4, -2, 5], [2,8,7]]) 

b = np.linalg.det(a)
b

-306.0

In [54]:
#Q10

b = np.arange(20,40,2)
np.flip(b)


array([38, 36, 34, 32, 30, 28, 26, 24, 22, 20])